### ISSUE TITLE
docker-compose up error

### ISSUE THREAD

**Issue by borysbo** [Kong/docker-kong-js-pdk#6]
I'm running "docker-compose up" from powershell (admin) on my Windows 10 Enterprise I got the following:
Creating network "docker-kong-js-pdk_default" with the default driver
Building kong
Step 1/6 : FROM kong:latest
 ---> d5ef5ae48a05
Step 2/6 : USER root
 ---> Using cache
 ---> 011a2cbd85f0
Step 3/6 : RUN apk add --update nodejs npm python2 make g++
 ---> Using cache
 ---> e43355947de3
Step 4/6 : RUN npm install --unsafe -g kong-pdk@0.3.0
 ---> Running in 9822813dd0a4
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/kong-pdk/node_modules/msgpack
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory '/usr/local/lib/node_modules/kong-pdk/node_modules/msgpack/build'
npm ERR! make: Leaving directory '/usr/local/lib/node_modules/kong-pdk/node_modules/msgpack/build'
npm ERR! gyp info it worked if it ends with ok
...
...
ERROR: Service 'kong' failed to build : The command '/bin/sh -c npm install --unsafe -g kong-pdk@0.3.0' returned a non-zero code: 1

**Comment by mheap** [comment]
This was resolved in https://github.com/Kong/docker-kong-js-pdk/commit/7121c6703754618414d8a300b834596ba6851a6d I believe
